### ISSUE TITLE
Tests fail occasionally with "No mapping between account names and security IDs was done."

### ISSUE THREAD

**Issue by brannon** [cloudfoundry-incubator/if_warden#9]
The LocalPrincipalManager tests fail occasionally with the above error.

I believe it is related to some eventual consistency in Windows with creating a new user, and then trying to add that user to a security group.  The error suggests that the failure was in mapping a username to a SID.

We should consider polling (in the code) to ensure that the user exists and can be mapped to a SID, before continuing and trying to use the new user.

**Comment by brannon** [comment]
Here is an example stack trace:

```
Test Name:    IronFoundry.Container.Utilities.LocalPrincipalManagerTests.AddedUserAppearsInWardenGroup
Test FullName:    IronFoundry.Container.Utilities.LocalPrincipalManagerTests.AddedUserAppearsInWardenGroup
Test Source:    c:\git\if\if_warden\IronFoundry.Container.Test\Utilities\LocalPrincipalManagerTests.cs : line 62
Test Outcome:    Failed
Test Duration:    0:00:00.164

Result Message:    System.Runtime.InteropServices.COMException : No mapping between account names and security IDs was done.
Result StackTrace:    
at System.DirectoryServices.PropertyValueCollection.PopulateList()
  at System.DirectoryServices.PropertyValueCollection..ctor(DirectoryEntry entry, String propertyName)
  at System.DirectoryServices.PropertyCollection.get_Item(String propertyName)
  at System.DirectoryServices.AccountManagement.QbeMatcher.Matches(DirectoryEntry de)
  at System.DirectoryServices.AccountManagement.SAMQuerySet.MoveNext()
  at System.DirectoryServices.AccountManagement.FindResultEnumerator`1.MoveNext()
  at System.DirectoryServices.AccountManagement.PrincipalSearcher.FindOne()
  at IronFoundry.Container.Utilities.LocalPrincipalManager.AddUserToGroup(PrincipalContext context, String groupName, UserPrincipal user) in c:\git\if\if_warden\IronFoundry.Container.Shared\Utilities\LocalPrincipalManager.cs:line 151
  at IronFoundry.Container.Utilities.LocalPrincipalManager.InnerCreateUser(String userName) in c:\git\if\if_warden\IronFoundry.Container.Shared\Utilities\LocalPrincipalManager.cs:line 136
  at IronFoundry.Container.Utilities.LocalPrincipalManager.CreateUser(String userName) in c:\git\if\if_warden\IronFoundry.Container.Shared\Utilities\LocalPrincipalManager.cs:line 59
  at IronFoundry.Container.Utilities.LocalPrincipalManagerTests.AddedUserAppearsInWardenGroup() in c:\git\if\if_warden\IronFoundry.Container.Test\Utilities\LocalPrincipalManagerTests.cs:line 63
```

**Comment by mosoto** [comment]
Error Code for this is: 0x80070534
